# Generated by Django 4.2.2 on 2023-10-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalOperations', '0006_userhos'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldetails',
            name='addressLine',
            field=models.CharField(default=None, max_length=3000),
        ),
        migrations.AddField(
            model_name='userhos',
            name='date_of_sent',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
