# Generated by Django 4.2.2 on 2023-10-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalOperations', '0009_rename_bloodinml_userhos_bloodinunits'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhos',
            name='location',
            field=models.CharField(null=True),
        ),
    ]
