# Generated by Django 4.2.2 on 2023-10-01 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalOperations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageRequested', models.CharField(max_length=2000)),
                ('RequestApproved', models.BooleanField()),
                ('hos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalOperations.hospitallogin')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=1500)),
                ('state', models.CharField(max_length=1500)),
                ('country', models.CharField(max_length=1500)),
                ('postal_code', models.CharField(max_length=150)),
                ('country_code', models.CharField(max_length=10)),
                ('locality', models.CharField(max_length=1500)),
                ('phone_number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=1500)),
                ('last_logined', models.DateTimeField(auto_now_add=True)),
                ('last_logined_location', models.CharField(max_length=1500)),
                ('updated_loction', models.CharField(max_length=1500)),
                ('hos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalOperations.hospitallogin')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalBloodBanks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A_Positive', models.CharField(max_length=90)),
                ('B_Positive', models.CharField(max_length=90)),
                ('AB_Positive', models.CharField(max_length=90)),
                ('O_Positive', models.CharField(max_length=90)),
                ('A_Negative', models.CharField(max_length=90)),
                ('B_Negative', models.CharField(max_length=90)),
                ('AB_Negative', models.CharField(max_length=90)),
                ('O_Negative', models.CharField(max_length=90)),
                ('hos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalOperations.hospitallogin')),
            ],
        ),
    ]
