# Generated by Django 4.2.2 on 2023-10-01 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalOperations', '0002_userhos_hospitaldetails_hospitalbloodbanks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHos',
        ),
    ]
