# Generated by Django 4.2.2 on 2023-10-01 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalOperations', '0004_userhos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHos',
        ),
    ]
