# Generated by Django 4.2.2 on 2023-10-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalOperations', '0007_hospitaldetails_addressline_userhos_date_of_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhos',
            name='date_of_sent',
            field=models.DateTimeField(default=None),
        ),
    ]
