# Generated by Django 4.2.2 on 2023-10-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalOperations', '0010_userhos_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhos',
            name='BloodGroupAloted',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='userhos',
            name='RequestApproved',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='userhos',
            name='date_of_approved',
            field=models.DateTimeField(null=True),
        ),
    ]
