# Generated by Django 4.2.6 on 2023-11-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalOperations', '0011_alter_userhos_bloodgroupaloted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitallogin',
            name='HosName',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='hospitallogin',
            name='hosUsername',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
