# Generated by Django 4.2.6 on 2023-11-09 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_userlogin_username'),
        ('hospitalOperations', '0012_alter_hospitallogin_hosname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdminHos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalOperations.hospitallogin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.userlogin')),
            ],
        ),
    ]
