# Generated by Django 4.2.2 on 2023-10-01 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_last_logiend_userdetails_last_loginend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='last_loginend',
            new_name='last_logined',
        ),
    ]
