# Generated by Django 4.2.2 on 2023-10-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_rename_last_loginend_userdetails_last_logined'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='img',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
