# Generated by Django 4.2.6 on 2023-11-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_userlogin_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='username',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
