# Generated by Django 4.2.2 on 2023-10-01 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_userlogin_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='last_logiend',
            new_name='last_loginend',
        ),
    ]
